### ISSUE TITLE
Still Usable?

### ISSUE THREAD

**Issue by AcrimoniousMirth** [cmpute/pypcl#3]
Hi, I see you're no longer supporting this. That's a shame as it'd have been so useful!
As things stand I need to tessellate a mesh of form `[[x1 y1 z1][x2 y2 z2]...[xn yn zn]]` on my RPi and export it as an STL. Will this library still support that?

**Comment by cmpute** [comment]
There exists an unofficial python binding for PCL, which probably meets your demand. I don't have much time to develop this now.

**Comment by cmpute** [comment]
This library is now turned into cython binding of PCL, you can have a try. The support of mesh has not been implemented both on pure python and cython. If you still have need for mesh support, please open a new issue instead. Thanks!
