### ISSUE TITLE
from ._pcl import *

### ISSUE THREAD

**Issue by liveforday** [cmpute/pypcl#5]
I have installed the package  successfully but there is an error when i import pcl moddule.
`from ._pcl import *` this code in __init__.py 
It remmand me   'no Module‘
I use win10 64 system

**Comment by SpartanBin** [comment]
I have the same problem with you. Did you fix it?

**Comment by cmpute** [comment]
Could you post the installation log here? I think it may be associated with the extension build process.
BTW, this project may be no longer developed because I didn't have any key reason to rewrite the whole package. I'm trying to build a user friendly python binding now.

**Comment by cmpute** [comment]
The master code is changed to cython implementation. If the problem still exists, please feel free to reopen the issue :)
